################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../forbackup/src/internet/model/arp-cache.cc \
../forbackup/src/internet/model/arp-header.cc \
../forbackup/src/internet/model/arp-l3-protocol.cc \
../forbackup/src/internet/model/candidate-queue.cc \
../forbackup/src/internet/model/global-route-manager-impl.cc \
../forbackup/src/internet/model/global-route-manager.cc \
../forbackup/src/internet/model/global-router-interface.cc \
../forbackup/src/internet/model/icmpv4-l4-protocol.cc \
../forbackup/src/internet/model/icmpv4.cc \
../forbackup/src/internet/model/icmpv6-header.cc \
../forbackup/src/internet/model/icmpv6-l4-protocol.cc \
../forbackup/src/internet/model/ip-l4-protocol.cc \
../forbackup/src/internet/model/ipv4-address-generator.cc \
../forbackup/src/internet/model/ipv4-end-point-demux.cc \
../forbackup/src/internet/model/ipv4-end-point.cc \
../forbackup/src/internet/model/ipv4-global-routing.cc \
../forbackup/src/internet/model/ipv4-header.cc \
../forbackup/src/internet/model/ipv4-interface-address.cc \
../forbackup/src/internet/model/ipv4-interface.cc \
../forbackup/src/internet/model/ipv4-l3-protocol.cc \
../forbackup/src/internet/model/ipv4-list-routing.cc \
../forbackup/src/internet/model/ipv4-packet-filter.cc \
../forbackup/src/internet/model/ipv4-packet-info-tag.cc \
../forbackup/src/internet/model/ipv4-packet-probe.cc \
../forbackup/src/internet/model/ipv4-queue-disc-item.cc \
../forbackup/src/internet/model/ipv4-raw-socket-factory-impl.cc \
../forbackup/src/internet/model/ipv4-raw-socket-factory.cc \
../forbackup/src/internet/model/ipv4-raw-socket-impl.cc \
../forbackup/src/internet/model/ipv4-route.cc \
../forbackup/src/internet/model/ipv4-routing-protocol.cc \
../forbackup/src/internet/model/ipv4-routing-table-entry.cc \
../forbackup/src/internet/model/ipv4-static-routing.cc \
../forbackup/src/internet/model/ipv4.cc \
../forbackup/src/internet/model/ipv6-address-generator.cc \
../forbackup/src/internet/model/ipv6-autoconfigured-prefix.cc \
../forbackup/src/internet/model/ipv6-end-point-demux.cc \
../forbackup/src/internet/model/ipv6-end-point.cc \
../forbackup/src/internet/model/ipv6-extension-demux.cc \
../forbackup/src/internet/model/ipv6-extension-header.cc \
../forbackup/src/internet/model/ipv6-extension.cc \
../forbackup/src/internet/model/ipv6-header.cc \
../forbackup/src/internet/model/ipv6-interface-address.cc \
../forbackup/src/internet/model/ipv6-interface.cc \
../forbackup/src/internet/model/ipv6-l3-protocol.cc \
../forbackup/src/internet/model/ipv6-list-routing.cc \
../forbackup/src/internet/model/ipv6-option-demux.cc \
../forbackup/src/internet/model/ipv6-option-header.cc \
../forbackup/src/internet/model/ipv6-option.cc \
../forbackup/src/internet/model/ipv6-packet-filter.cc \
../forbackup/src/internet/model/ipv6-packet-info-tag.cc \
../forbackup/src/internet/model/ipv6-packet-probe.cc \
../forbackup/src/internet/model/ipv6-pmtu-cache.cc \
../forbackup/src/internet/model/ipv6-queue-disc-item.cc \
../forbackup/src/internet/model/ipv6-raw-socket-factory-impl.cc \
../forbackup/src/internet/model/ipv6-raw-socket-factory.cc \
../forbackup/src/internet/model/ipv6-raw-socket-impl.cc \
../forbackup/src/internet/model/ipv6-route.cc \
../forbackup/src/internet/model/ipv6-routing-protocol.cc \
../forbackup/src/internet/model/ipv6-routing-table-entry.cc \
../forbackup/src/internet/model/ipv6-static-routing.cc \
../forbackup/src/internet/model/ipv6.cc \
../forbackup/src/internet/model/loopback-net-device.cc \
../forbackup/src/internet/model/mptcp-cc-coupled.cc \
../forbackup/src/internet/model/mptcp-cc-olia.cc \
../forbackup/src/internet/model/mptcp-crypto.cc \
../forbackup/src/internet/model/mptcp-id-manager-impl.cc \
../forbackup/src/internet/model/mptcp-id-manager.cc \
../forbackup/src/internet/model/mptcp-lia.cc \
../forbackup/src/internet/model/mptcp-mapping.cc \
../forbackup/src/internet/model/mptcp-scheduler-fastest-rtt.cc \
../forbackup/src/internet/model/mptcp-scheduler-largest-dbp.cc \
../forbackup/src/internet/model/mptcp-scheduler-random.cc \
../forbackup/src/internet/model/mptcp-scheduler-round-robin.cc \
../forbackup/src/internet/model/mptcp-scheduler.cc \
../forbackup/src/internet/model/mptcp-socket-factory.cc \
../forbackup/src/internet/model/mptcp-subflow.cc \
../forbackup/src/internet/model/ndisc-cache.cc \
../forbackup/src/internet/model/nsc-sysctl.cc \
../forbackup/src/internet/model/nsc-tcp-l4-protocol.cc \
../forbackup/src/internet/model/nsc-tcp-socket-factory-impl.cc \
../forbackup/src/internet/model/nsc-tcp-socket-impl.cc \
../forbackup/src/internet/model/pending-data.cc \
../forbackup/src/internet/model/rip-header.cc \
../forbackup/src/internet/model/rip.cc \
../forbackup/src/internet/model/ripng-header.cc \
../forbackup/src/internet/model/ripng.cc \
../forbackup/src/internet/model/rl-data-interface.cc \
../forbackup/src/internet/model/rl-realSocket.cc \
../forbackup/src/internet/model/rtt-estimator.cc \
../forbackup/src/internet/model/tcp-bic.cc \
../forbackup/src/internet/model/tcp-congestion-ops.cc \
../forbackup/src/internet/model/tcp-header.cc \
../forbackup/src/internet/model/tcp-highspeed.cc \
../forbackup/src/internet/model/tcp-hybla.cc \
../forbackup/src/internet/model/tcp-illinois.cc \
../forbackup/src/internet/model/tcp-l4-protocol.cc \
../forbackup/src/internet/model/tcp-old-socket-base.cc \
../forbackup/src/internet/model/tcp-option-mptcp.cc \
../forbackup/src/internet/model/tcp-option-rfc793.cc \
../forbackup/src/internet/model/tcp-option-ts.cc \
../forbackup/src/internet/model/tcp-option-winscale.cc \
../forbackup/src/internet/model/tcp-option.cc \
../forbackup/src/internet/model/tcp-parameters.cc \
../forbackup/src/internet/model/tcp-rx-buffer.cc \
../forbackup/src/internet/model/tcp-scalable.cc \
../forbackup/src/internet/model/tcp-socket-base.cc \
../forbackup/src/internet/model/tcp-socket-factory-impl.cc \
../forbackup/src/internet/model/tcp-socket-factory.cc \
../forbackup/src/internet/model/tcp-socket-state.cc \
../forbackup/src/internet/model/tcp-socket-wrapper.cc \
../forbackup/src/internet/model/tcp-socket.cc \
../forbackup/src/internet/model/tcp-tx-buffer.cc \
../forbackup/src/internet/model/tcp-vegas.cc \
../forbackup/src/internet/model/tcp-veno.cc \
../forbackup/src/internet/model/tcp-westwood.cc \
../forbackup/src/internet/model/tcp-yeah.cc \
../forbackup/src/internet/model/udp-header.cc \
../forbackup/src/internet/model/udp-l4-protocol.cc \
../forbackup/src/internet/model/udp-socket-factory-impl.cc \
../forbackup/src/internet/model/udp-socket-factory.cc \
../forbackup/src/internet/model/udp-socket-impl.cc \
../forbackup/src/internet/model/udp-socket.cc 

CC_DEPS += \
./forbackup/src/internet/model/arp-cache.d \
./forbackup/src/internet/model/arp-header.d \
./forbackup/src/internet/model/arp-l3-protocol.d \
./forbackup/src/internet/model/candidate-queue.d \
./forbackup/src/internet/model/global-route-manager-impl.d \
./forbackup/src/internet/model/global-route-manager.d \
./forbackup/src/internet/model/global-router-interface.d \
./forbackup/src/internet/model/icmpv4-l4-protocol.d \
./forbackup/src/internet/model/icmpv4.d \
./forbackup/src/internet/model/icmpv6-header.d \
./forbackup/src/internet/model/icmpv6-l4-protocol.d \
./forbackup/src/internet/model/ip-l4-protocol.d \
./forbackup/src/internet/model/ipv4-address-generator.d \
./forbackup/src/internet/model/ipv4-end-point-demux.d \
./forbackup/src/internet/model/ipv4-end-point.d \
./forbackup/src/internet/model/ipv4-global-routing.d \
./forbackup/src/internet/model/ipv4-header.d \
./forbackup/src/internet/model/ipv4-interface-address.d \
./forbackup/src/internet/model/ipv4-interface.d \
./forbackup/src/internet/model/ipv4-l3-protocol.d \
./forbackup/src/internet/model/ipv4-list-routing.d \
./forbackup/src/internet/model/ipv4-packet-filter.d \
./forbackup/src/internet/model/ipv4-packet-info-tag.d \
./forbackup/src/internet/model/ipv4-packet-probe.d \
./forbackup/src/internet/model/ipv4-queue-disc-item.d \
./forbackup/src/internet/model/ipv4-raw-socket-factory-impl.d \
./forbackup/src/internet/model/ipv4-raw-socket-factory.d \
./forbackup/src/internet/model/ipv4-raw-socket-impl.d \
./forbackup/src/internet/model/ipv4-route.d \
./forbackup/src/internet/model/ipv4-routing-protocol.d \
./forbackup/src/internet/model/ipv4-routing-table-entry.d \
./forbackup/src/internet/model/ipv4-static-routing.d \
./forbackup/src/internet/model/ipv4.d \
./forbackup/src/internet/model/ipv6-address-generator.d \
./forbackup/src/internet/model/ipv6-autoconfigured-prefix.d \
./forbackup/src/internet/model/ipv6-end-point-demux.d \
./forbackup/src/internet/model/ipv6-end-point.d \
./forbackup/src/internet/model/ipv6-extension-demux.d \
./forbackup/src/internet/model/ipv6-extension-header.d \
./forbackup/src/internet/model/ipv6-extension.d \
./forbackup/src/internet/model/ipv6-header.d \
./forbackup/src/internet/model/ipv6-interface-address.d \
./forbackup/src/internet/model/ipv6-interface.d \
./forbackup/src/internet/model/ipv6-l3-protocol.d \
./forbackup/src/internet/model/ipv6-list-routing.d \
./forbackup/src/internet/model/ipv6-option-demux.d \
./forbackup/src/internet/model/ipv6-option-header.d \
./forbackup/src/internet/model/ipv6-option.d \
./forbackup/src/internet/model/ipv6-packet-filter.d \
./forbackup/src/internet/model/ipv6-packet-info-tag.d \
./forbackup/src/internet/model/ipv6-packet-probe.d \
./forbackup/src/internet/model/ipv6-pmtu-cache.d \
./forbackup/src/internet/model/ipv6-queue-disc-item.d \
./forbackup/src/internet/model/ipv6-raw-socket-factory-impl.d \
./forbackup/src/internet/model/ipv6-raw-socket-factory.d \
./forbackup/src/internet/model/ipv6-raw-socket-impl.d \
./forbackup/src/internet/model/ipv6-route.d \
./forbackup/src/internet/model/ipv6-routing-protocol.d \
./forbackup/src/internet/model/ipv6-routing-table-entry.d \
./forbackup/src/internet/model/ipv6-static-routing.d \
./forbackup/src/internet/model/ipv6.d \
./forbackup/src/internet/model/loopback-net-device.d \
./forbackup/src/internet/model/mptcp-cc-coupled.d \
./forbackup/src/internet/model/mptcp-cc-olia.d \
./forbackup/src/internet/model/mptcp-crypto.d \
./forbackup/src/internet/model/mptcp-id-manager-impl.d \
./forbackup/src/internet/model/mptcp-id-manager.d \
./forbackup/src/internet/model/mptcp-lia.d \
./forbackup/src/internet/model/mptcp-mapping.d \
./forbackup/src/internet/model/mptcp-scheduler-fastest-rtt.d \
./forbackup/src/internet/model/mptcp-scheduler-largest-dbp.d \
./forbackup/src/internet/model/mptcp-scheduler-random.d \
./forbackup/src/internet/model/mptcp-scheduler-round-robin.d \
./forbackup/src/internet/model/mptcp-scheduler.d \
./forbackup/src/internet/model/mptcp-socket-factory.d \
./forbackup/src/internet/model/mptcp-subflow.d \
./forbackup/src/internet/model/ndisc-cache.d \
./forbackup/src/internet/model/nsc-sysctl.d \
./forbackup/src/internet/model/nsc-tcp-l4-protocol.d \
./forbackup/src/internet/model/nsc-tcp-socket-factory-impl.d \
./forbackup/src/internet/model/nsc-tcp-socket-impl.d \
./forbackup/src/internet/model/pending-data.d \
./forbackup/src/internet/model/rip-header.d \
./forbackup/src/internet/model/rip.d \
./forbackup/src/internet/model/ripng-header.d \
./forbackup/src/internet/model/ripng.d \
./forbackup/src/internet/model/rl-data-interface.d \
./forbackup/src/internet/model/rl-realSocket.d \
./forbackup/src/internet/model/rtt-estimator.d \
./forbackup/src/internet/model/tcp-bic.d \
./forbackup/src/internet/model/tcp-congestion-ops.d \
./forbackup/src/internet/model/tcp-header.d \
./forbackup/src/internet/model/tcp-highspeed.d \
./forbackup/src/internet/model/tcp-hybla.d \
./forbackup/src/internet/model/tcp-illinois.d \
./forbackup/src/internet/model/tcp-l4-protocol.d \
./forbackup/src/internet/model/tcp-old-socket-base.d \
./forbackup/src/internet/model/tcp-option-mptcp.d \
./forbackup/src/internet/model/tcp-option-rfc793.d \
./forbackup/src/internet/model/tcp-option-ts.d \
./forbackup/src/internet/model/tcp-option-winscale.d \
./forbackup/src/internet/model/tcp-option.d \
./forbackup/src/internet/model/tcp-parameters.d \
./forbackup/src/internet/model/tcp-rx-buffer.d \
./forbackup/src/internet/model/tcp-scalable.d \
./forbackup/src/internet/model/tcp-socket-base.d \
./forbackup/src/internet/model/tcp-socket-factory-impl.d \
./forbackup/src/internet/model/tcp-socket-factory.d \
./forbackup/src/internet/model/tcp-socket-state.d \
./forbackup/src/internet/model/tcp-socket-wrapper.d \
./forbackup/src/internet/model/tcp-socket.d \
./forbackup/src/internet/model/tcp-tx-buffer.d \
./forbackup/src/internet/model/tcp-vegas.d \
./forbackup/src/internet/model/tcp-veno.d \
./forbackup/src/internet/model/tcp-westwood.d \
./forbackup/src/internet/model/tcp-yeah.d \
./forbackup/src/internet/model/udp-header.d \
./forbackup/src/internet/model/udp-l4-protocol.d \
./forbackup/src/internet/model/udp-socket-factory-impl.d \
./forbackup/src/internet/model/udp-socket-factory.d \
./forbackup/src/internet/model/udp-socket-impl.d \
./forbackup/src/internet/model/udp-socket.d 

OBJS += \
./forbackup/src/internet/model/arp-cache.o \
./forbackup/src/internet/model/arp-header.o \
./forbackup/src/internet/model/arp-l3-protocol.o \
./forbackup/src/internet/model/candidate-queue.o \
./forbackup/src/internet/model/global-route-manager-impl.o \
./forbackup/src/internet/model/global-route-manager.o \
./forbackup/src/internet/model/global-router-interface.o \
./forbackup/src/internet/model/icmpv4-l4-protocol.o \
./forbackup/src/internet/model/icmpv4.o \
./forbackup/src/internet/model/icmpv6-header.o \
./forbackup/src/internet/model/icmpv6-l4-protocol.o \
./forbackup/src/internet/model/ip-l4-protocol.o \
./forbackup/src/internet/model/ipv4-address-generator.o \
./forbackup/src/internet/model/ipv4-end-point-demux.o \
./forbackup/src/internet/model/ipv4-end-point.o \
./forbackup/src/internet/model/ipv4-global-routing.o \
./forbackup/src/internet/model/ipv4-header.o \
./forbackup/src/internet/model/ipv4-interface-address.o \
./forbackup/src/internet/model/ipv4-interface.o \
./forbackup/src/internet/model/ipv4-l3-protocol.o \
./forbackup/src/internet/model/ipv4-list-routing.o \
./forbackup/src/internet/model/ipv4-packet-filter.o \
./forbackup/src/internet/model/ipv4-packet-info-tag.o \
./forbackup/src/internet/model/ipv4-packet-probe.o \
./forbackup/src/internet/model/ipv4-queue-disc-item.o \
./forbackup/src/internet/model/ipv4-raw-socket-factory-impl.o \
./forbackup/src/internet/model/ipv4-raw-socket-factory.o \
./forbackup/src/internet/model/ipv4-raw-socket-impl.o \
./forbackup/src/internet/model/ipv4-route.o \
./forbackup/src/internet/model/ipv4-routing-protocol.o \
./forbackup/src/internet/model/ipv4-routing-table-entry.o \
./forbackup/src/internet/model/ipv4-static-routing.o \
./forbackup/src/internet/model/ipv4.o \
./forbackup/src/internet/model/ipv6-address-generator.o \
./forbackup/src/internet/model/ipv6-autoconfigured-prefix.o \
./forbackup/src/internet/model/ipv6-end-point-demux.o \
./forbackup/src/internet/model/ipv6-end-point.o \
./forbackup/src/internet/model/ipv6-extension-demux.o \
./forbackup/src/internet/model/ipv6-extension-header.o \
./forbackup/src/internet/model/ipv6-extension.o \
./forbackup/src/internet/model/ipv6-header.o \
./forbackup/src/internet/model/ipv6-interface-address.o \
./forbackup/src/internet/model/ipv6-interface.o \
./forbackup/src/internet/model/ipv6-l3-protocol.o \
./forbackup/src/internet/model/ipv6-list-routing.o \
./forbackup/src/internet/model/ipv6-option-demux.o \
./forbackup/src/internet/model/ipv6-option-header.o \
./forbackup/src/internet/model/ipv6-option.o \
./forbackup/src/internet/model/ipv6-packet-filter.o \
./forbackup/src/internet/model/ipv6-packet-info-tag.o \
./forbackup/src/internet/model/ipv6-packet-probe.o \
./forbackup/src/internet/model/ipv6-pmtu-cache.o \
./forbackup/src/internet/model/ipv6-queue-disc-item.o \
./forbackup/src/internet/model/ipv6-raw-socket-factory-impl.o \
./forbackup/src/internet/model/ipv6-raw-socket-factory.o \
./forbackup/src/internet/model/ipv6-raw-socket-impl.o \
./forbackup/src/internet/model/ipv6-route.o \
./forbackup/src/internet/model/ipv6-routing-protocol.o \
./forbackup/src/internet/model/ipv6-routing-table-entry.o \
./forbackup/src/internet/model/ipv6-static-routing.o \
./forbackup/src/internet/model/ipv6.o \
./forbackup/src/internet/model/loopback-net-device.o \
./forbackup/src/internet/model/mptcp-cc-coupled.o \
./forbackup/src/internet/model/mptcp-cc-olia.o \
./forbackup/src/internet/model/mptcp-crypto.o \
./forbackup/src/internet/model/mptcp-id-manager-impl.o \
./forbackup/src/internet/model/mptcp-id-manager.o \
./forbackup/src/internet/model/mptcp-lia.o \
./forbackup/src/internet/model/mptcp-mapping.o \
./forbackup/src/internet/model/mptcp-scheduler-fastest-rtt.o \
./forbackup/src/internet/model/mptcp-scheduler-largest-dbp.o \
./forbackup/src/internet/model/mptcp-scheduler-random.o \
./forbackup/src/internet/model/mptcp-scheduler-round-robin.o \
./forbackup/src/internet/model/mptcp-scheduler.o \
./forbackup/src/internet/model/mptcp-socket-factory.o \
./forbackup/src/internet/model/mptcp-subflow.o \
./forbackup/src/internet/model/ndisc-cache.o \
./forbackup/src/internet/model/nsc-sysctl.o \
./forbackup/src/internet/model/nsc-tcp-l4-protocol.o \
./forbackup/src/internet/model/nsc-tcp-socket-factory-impl.o \
./forbackup/src/internet/model/nsc-tcp-socket-impl.o \
./forbackup/src/internet/model/pending-data.o \
./forbackup/src/internet/model/rip-header.o \
./forbackup/src/internet/model/rip.o \
./forbackup/src/internet/model/ripng-header.o \
./forbackup/src/internet/model/ripng.o \
./forbackup/src/internet/model/rl-data-interface.o \
./forbackup/src/internet/model/rl-realSocket.o \
./forbackup/src/internet/model/rtt-estimator.o \
./forbackup/src/internet/model/tcp-bic.o \
./forbackup/src/internet/model/tcp-congestion-ops.o \
./forbackup/src/internet/model/tcp-header.o \
./forbackup/src/internet/model/tcp-highspeed.o \
./forbackup/src/internet/model/tcp-hybla.o \
./forbackup/src/internet/model/tcp-illinois.o \
./forbackup/src/internet/model/tcp-l4-protocol.o \
./forbackup/src/internet/model/tcp-old-socket-base.o \
./forbackup/src/internet/model/tcp-option-mptcp.o \
./forbackup/src/internet/model/tcp-option-rfc793.o \
./forbackup/src/internet/model/tcp-option-ts.o \
./forbackup/src/internet/model/tcp-option-winscale.o \
./forbackup/src/internet/model/tcp-option.o \
./forbackup/src/internet/model/tcp-parameters.o \
./forbackup/src/internet/model/tcp-rx-buffer.o \
./forbackup/src/internet/model/tcp-scalable.o \
./forbackup/src/internet/model/tcp-socket-base.o \
./forbackup/src/internet/model/tcp-socket-factory-impl.o \
./forbackup/src/internet/model/tcp-socket-factory.o \
./forbackup/src/internet/model/tcp-socket-state.o \
./forbackup/src/internet/model/tcp-socket-wrapper.o \
./forbackup/src/internet/model/tcp-socket.o \
./forbackup/src/internet/model/tcp-tx-buffer.o \
./forbackup/src/internet/model/tcp-vegas.o \
./forbackup/src/internet/model/tcp-veno.o \
./forbackup/src/internet/model/tcp-westwood.o \
./forbackup/src/internet/model/tcp-yeah.o \
./forbackup/src/internet/model/udp-header.o \
./forbackup/src/internet/model/udp-l4-protocol.o \
./forbackup/src/internet/model/udp-socket-factory-impl.o \
./forbackup/src/internet/model/udp-socket-factory.o \
./forbackup/src/internet/model/udp-socket-impl.o \
./forbackup/src/internet/model/udp-socket.o 


# Each subdirectory must supply rules for building sources it contributes
forbackup/src/internet/model/%.o: ../forbackup/src/internet/model/%.cc
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


